### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by MewesK** [PHPOffice/PHPExcel#1110]
The Excel5 wirter seems to have a problem with PHP 7.1.

```
PHPUnit_Framework_Error_Warning: A non-numeric value encountered
/home/travis/build/MewesK/TwigExcelBundle/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:73
/home/travis/build/MewesK/TwigExcelBundle/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel5/Worksheet.php:2869
/home/travis/build/MewesK/TwigExcelBundle/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel5/Worksheet.php:519
/home/travis/build/MewesK/TwigExcelBundle/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel5.php:187
```

The $errorStyle variable should never be a string once it reaches the last line. 
```
$errorStyle = $dataValidation->getType();
switch ($errorStyle) {
	case PHPExcel_Cell_DataValidation::STYLE_STOP:			$errorStyle = 0x00;		break;
	case PHPExcel_Cell_DataValidation::STYLE_WARNING:		$errorStyle = 0x01;		break;
	case PHPExcel_Cell_DataValidation::STYLE_INFORMATION:	$errorStyle = 0x02;		break;
}
$options |= $errorStyle << 4;
```

Is `->getType()` correct?
What should be the default value for $errorStyle if none of the switch options are used?

**Comment by PowerKiKi** [comment]
As you can see there are [several bugs with PHP 7.1](https://travis-ci.org/PHPOffice/PhpSpreadsheet/jobs/191519295) that were still not fixed. Please consider creating a PR against PhpSpreadsheet develop branch if you are able to find a solution.

**Comment by mmuman** [comment]
Hmm, from looking at the code the getter looks suspiciously like a bad copy-paste:

```php
				$type = $dataValidation->getType();
…
				$errorStyle = $dataValidation->getType();
```

Shouldn't it be getErrorStyle() the second time? 😔

**Comment by PowerKiKi** [comment]
@mmuman you are absolutely right. Interestingly enough the bug existed for at least 7 years, since 509f27e. I guess PHP 7.1 new strictness is a good thing ;-)

Fixed in PhpSpreadsheet

**Comment by mmuman** [comment]
Nice, one less !
I still have a bug in my case here, it just strips some cells either with CONCATENATE() in LO (it ends up as _xlfn.CONCAT) or with the concatenation operator & used more than once, but that's probably something else.

**Comment by PowerKiKi** [comment]
If you try PhpSpreadsheet and discover bugs, please consider creating PR to fix bugs (ideally covered by unit tests), because we are severely understaffed.

**Comment by mmuman** [comment]
Aren't we all? 😊

**Comment by Webstorm-IL** [comment]
I get this error also.
Its trigger when data type column empty or cell with text define as date type, The script try to convert as date and got an errors.

**Comment by PowerKiKi** [comment]
@Webstorm-IL, upgrade to PhpSpreadsheet, if you can, to get solved this.

**Comment by thomasdominic** [comment]
In the file Excel5.php https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Writer/Excel5.php#L372 ; 

The method stringFromColumnIndex The method expects an integer  while a string is given because this method return a string
					`

**Comment by chamath** [comment]
Is there any update for this issue? we are using phpoffice/phpexcel 1.8 for yii2.

**Comment by hhsadiq** [comment]
is this issue fixed?

**Comment by hhsadiq** [comment]
Still getting this exception.
php7
